# ---------- Stage 1: base with deps ----------
FROM node:22-bullseye-slim AS base

WORKDIR /app

# Install OS deps only if really needed (prisma builds, etc.)
RUN apt-get update && apt-get install -y \
    openssl \
    python3 \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy only what's needed to install deps
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile  --legacy-peer-deps

