import { Inter } from 'next/font/google'
import SwaggerUI from 'swagger-ui-react'
import 'swagger-ui-react/swagger-ui.css'


const inter = Inter({ subsets: ['latin'] })

export default function Page() {
  return (
    <>
      <title>SwaggerUI</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <main className={`${inter.className}`}>
        <SwaggerUI url="https://petstore3.swagger.io/api/v3/openapi.json" />
      </main>
    </>
  )
}
