openapi: 3.0.0
info:
  title: Agora API
  description: Public API for interacting with the Agora platform
  version: 0.1.0
servers:
  - url: vote.optimisim.io/api/v1
  description: Base URL for optimism production
components:
  schemas:
    Delegate:
      type: object
      properties:
        address:
          type: string
          example: "0xDa6d1F091B672C0f9e215eB9fa6B5a84bF2c5e11"
        votingPower:
          type: object
          properties:
            advanced:
              type: string
              example: "10000"
            direct:
              type: string
              example: "20000"
            total:
              type: string
              example: "30000"
        isCitizen:
          type: boolean
        email:
          type: string
        twitter:
          type: string
          example:
        discord:
          type: string
          exmaple:
        statement:
          type: string
          example: "hello! I am a great delegate for reasons xyz"
        leastValuableProposals:
          type: array
          item: ???
        mostValuableProposals:
          type: array
          item: ???
        openToSponsoringProposals:
          type: boolean
        topIssues:
          type: array
          item: ???
parameters:
   limitParam:
      name: limit
      in: query
      description: Limits the number of returned results
      required: false
      type: integer
      format: int32
   offsetParam:
      name: offset
      in: query
      description: Offset from which start returned results
      required: false
      type: integer
      format: int32
paths:
  /delegates:
    get:
      summary: Gets delegates
      description: Retrieves a list of voting delegates
      operationId: getDelegates
      parameters:
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/offsetParam"
        - name: sort
          in: query
          description: >-
            The desired method by which returned delegates will be sorted
          required: false
          schema: 
            type: string
      responses: 
        '200':
          description: successful operation
          content:
            application/json:
              schema: '#/components/schema/Delegate'