import Head from "next/head";
import { Inter } from "next/font/google";
import "swagger-ui-react/swagger-ui.css";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });
const DynamicSwaggerUI = dynamic(() => import("swagger-ui-react"), {
  ssr: false,
});

export default function Page() {
  return (
    <>
      <Head>
        <title>SwaggerUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <DynamicSwaggerUI url="https://petstore3.swagger.io/api/v3/openapi.json" />
      </main>
    </>
  );
}
