name: action-jira-linker
on: [pull_request]

jobs:
  action-jira-linter:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: exogee-technology/action-jira-linker@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-user: ${{ secrets.JIRA_USER }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://voteagora.atlassian.net
          comment-header: |
            ## JIRA Information
          comment-trailer: |
            Fix the governance, fix the world.
          fail-on-error: true
